language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "planeasy-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: plan-easy # see README
  api_key:
    secure: 'UAcJ4uTMdGG/THCOpziUFAsyhzT2rkPbLh6HKi9SrgjvvMaZP8X7qVCtILdBY5+bMv0IwKVHIGggHAWxq3n4VkzGbgbVBcTK/FqWbcYIfR1S9HpbIJ6HZWDYkDVc8tgDumhyvoO7JDk6CqCAYVARL2R/3m6qG2Uli3G7ZEE9b03E+AlxzszI9M7KC6BUhukQyggJq0FQDQkTE1vwHKQdseVYrUrIPwzTR5PoyhqM8ohQGZLIHpiRcgSkS+P3kHrBZLpiSmhIEGOdPSM7m12i+s4zgSkh6qInmIR3ETcmulPPaic3ai0KVYaTNJmg/D7G1rTr3skvUF9IoKuK+8k9XdcCCgiTUJ1PuM4vyLZ2AaK7DVqzAWtV6sumnVXxyGArbPIld6zc9gAJvg6ZPX3bM1CRLWzuqM1C72F0fk1+JbFRQ8bUCl/KzvKfAc8Ph+28xUfAtf0mfQH97TiMCMK7jl7yMy4qGw/+eacZ1F9KSwPvNPuLrbozlY1D2DPOKTW+AUfqekaWuu/l97jStkSglH9y3oGy1zRd6TPKwwHqYnFchgd3Rl7vS621mqvdY54wpwwzil3fpi4PyVxO0WLDrdKfBerl2tU7UjBfkTUvhW6E1WOrQ0e+vxvdrIDOB6+WnBk/sq4kLHaKXpANYoPRpZ/X+BxYe+hQXXqy5mD1Z18=" # see README
